-- ============================================================
-- BASE DE DATOS - BANKING MICROSERVICES
-- ============================================================

-- ============================================================
-- CUSTOMER SERVICE
-- Base de datos: banking_customer
-- ============================================================

CREATE TABLE IF NOT EXISTS persona (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255),
    genero VARCHAR(255),
    edad INTEGER,
    identificacion VARCHAR(255),
    direccion VARCHAR(255),
    telefono VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS cliente (
    id BIGINT PRIMARY KEY,
    cliente_id BIGINT NOT NULL UNIQUE,
    contrasena VARCHAR(255),
    estado BOOLEAN,

    CONSTRAINT fk_cliente_persona
        FOREIGN KEY (id)
        REFERENCES persona(id)
);

-- ============================================================
-- ACCOUNT SERVICE
-- Base de datos: banking_account
-- ============================================================

CREATE TABLE IF NOT EXISTS cuenta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_cuenta BIGINT NOT NULL UNIQUE,
    tipo_cuenta VARCHAR(255) NOT NULL,
    saldo NUMERIC(15,2) NOT NULL,
    estado BOOLEAN NOT NULL,
    cliente_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS movimiento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha TIMESTAMP(6) NOT NULL,
    tipo_movimiento VARCHAR(255) NOT NULL,
    valor NUMERIC(15,2) NOT NULL,
    saldo NUMERIC(15,2) NOT NULL,
    cuenta_id BIGINT NOT NULL,

    CONSTRAINT fk_movimiento_cuenta
        FOREIGN KEY (cuenta_id)
        REFERENCES cuenta(id)
);